SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES FROM BOOK_SALES S, BOOK B, AUTHOR A
WHERE YEAR(S.SALES_DATE)=2022 AND MONTH(S.SALES_DATE)=1
  AND B.BOOK_ID = S.BOOK_ID
  AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC