SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE B.STATUS = 'DONE' AND B.WRITER_ID = U.USER_ID
GROUP BY B.WRITER_ID HAVING SUM(B.PRICE) >= 700000
ORDER BY SUM(B.PRICE)