# SELECT MEMBER_ID, MAX(MAX_MEMBER) FROM
# (
#     SELECT MEMBER_ID, COUNT(MEMBER_ID) AS MAX_MEMBER
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
# ) AS COUNTS

# SELECT R.MEMBER_ID FROM MEMBER_PROFILE M, REST_REVIEW R
#     WHERE M.MEMBER_ID = R.MEMBER_ID
#     GROUP BY MEMBER_ID
#     ORDER BY COUNT(R.MEMBER_ID) DESC
#     LIMIT 1

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M, REST_REVIEW R
WHERE M.MEMBER_ID =
    (SELECT R.MEMBER_ID FROM MEMBER_PROFILE M, REST_REVIEW R
    WHERE M.MEMBER_ID = R.MEMBER_ID
    GROUP BY MEMBER_ID
    ORDER BY COUNT(R.MEMBER_ID) DESC
    LIMIT 1)
    AND M.MEMBER_ID = R.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT