# SELECT * FROM ANIMAL_INS
# SELECT * FROM ANIMAL_OUTS

# SELECT O.DATETIME AS 입양일, I.DATETIME AS 보호시작일
# FROM ANIMAL_INS I, ANIMAL_OUTS O
# WHERE I.ANIMAL_ID = O.ANIMAL_ID AND O.DATETIME < I.DATETIME
# ORDER BY I.DATETIME

SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID AND O.DATETIME < I.DATETIME
ORDER BY I.DATETIME