# SELECT * FROM ICECREAM_INFO
# SELECT * FROM FIRST_HALF

SELECT DISTINCT FLAVOR FROM FIRST_HALF
WHERE FLAVOR = ANY(SELECT DISTINCT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE='fruit_based') AND TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC