SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D, HR_EMPLOYEES E, HR_GRADE G
WHERE D.DEPT_ID = E.DEPT_ID
  AND E.EMP_NO = G.EMP_NO
  AND G.YEAR=2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1
  
  # G.SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL